Add a success message to single route tasks
Now that these tasks are being called from the command line, and not a Jenkins job,
we should give some feedback to the user the that task has completed successfully.

The code in the `unpublish_one_route` class method has been moved to an instance
method to allow logging as `logger` can only be called within an instance of the class:

```
NameError:
       undefined local variable or method `logger' for SpecialRoutePublisher:Class

             logger.info("Path #{route} unpublished")
             ^^^^^^
     # ./lib/special_route_publisher.rb:39:in `unpublish_one_route'
```